---
title: "LSH Ent Data Pin"
author: "Ryan Johnson"
date: "5/20/2021"
output: html_document
---

# Connect to SF

```{r warning=F, message=F}
library(tidyverse)
library(odbc)
library(DBI)
library(dbplyr)
library(lubridate)

# Setup connections
con <- DBI::dbConnect(odbc::odbc(),
                      database = "marketing", 
                      Driver = "Redshift",
                      host = "redhouse.cyii7eabibhu.us-east-1.redshift.amazonaws.com", 
                      port = 5439, 
                      UID = Sys.getenv("WAREHOUSE_USER"), 
                      PWD = Sys.getenv("WAREHOUSE_PASSWORD"))
```


# Create LSH-Ent Table

```{r}
# Get Account names
account_info <- tbl(con, in_schema("salesforce", "account")) %>%
  filter(pod_team_c == "Ent LSH") %>% 
  filter(is_deleted == "0") %>% 
  filter(type == "Customer") %>% 
  select(acct_id = id, acct_name = name,
         acct_cs_owner_id = customer_success_team_member_c,
         acct_owner_id = owner_id, acct_acv = annual_contract_value_c) %>%
  collect()

# Get Open Opps
open_opps <- tbl(con, in_schema("salesforce", "opportunity")) %>% 
  filter(is_deleted == "0") %>%
  filter(!stage_name %in% c("Closed Won", "Closed Lost", "Opportunity Disqualified")) %>% 
  select(opp_id = id, acct_id = account_id, opp_name = name, opp_stage_name = stage_name,
         opp_amount = amount, opp_close_date = close_date, opp_license_start_date = license_start_date_c) %>% 
  collect() %>% 
  filter(acct_id %in% account_info$acct_id)

# Get RStudio IDs and name
rstudio_contacts <- tbl(con, in_schema("salesforce", "user")) %>%
  select(first_name, last_name, id) %>% 
  collect() %>% 
  unite("rstudio_contact_name", c("first_name", "last_name"), sep = " ") %>% 
  rename(rstudio_contact_id = id)
```

# Merge into Final Table
```{r}
final_table <- open_opps %>% 
  left_join(account_info, by = "acct_id") %>% 
  # Add in RStudio names
  left_join(rstudio_contacts, by = c("acct_owner_id" = "rstudio_contact_id")) %>%
  rename(acct_owner_name = rstudio_contact_name) %>% 
  left_join(rstudio_contacts, by = c("acct_cs_owner_id" = "rstudio_contact_id")) %>%
  rename(acct_cs_owner_name = rstudio_contact_name)
```
